### ISSUE TITLE
Stardew vally mod manager won't start. 

### ISSUE THREAD

**Issue by Homex5** [yuukiw/StardewValleyMM#16]
hey guys the mod manager wont open and i tried the other techniques but wont work, or im just incapaperble to make it work. but it would help me dearly if some one would help me through this because the game is worth playing with mods. 

here is the error

Unhandled Exception: System.TypeLoadException: Could not load type 'LanguageCode' from assembly 'Stardew Valley, Version=1.0.6124.25603, Culture=neutral, PublicKeyToken=null'.
   at StardewModdingAPI.Program.RunInteractively()
   at StardewModdingAPI.Program.Main(String[] args) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Program.cs:line 95

**Comment by yuukiw** [comment]
update your game and it should fix it self. It happens due a Version missmatch.

**Comment by Homex5** [comment]
thx a bunch 
reminds me to subscribe 👍
